name: Aggregate

on:
  schedule:
    - cron:  '50 2 * * *'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Collect and aggregate data
      run: python aggregate.py
    
    - name: Commiting changes
      uses: stefanzweifel/git-auto-commit-action@v4.3.0
      with:
        commit_message: 'updating data...'












